---
title: "R Notebook"
author: "Resham Chana"
output:
  html_document:
    toc: yes
    df_print: paged
---

```{r, echo=FALSE, error = FALSE, resutls = "hide"}
my_packages <- c(
  "tidyverse", "here", "lubridate", "leaflet", "readxl", "XML",
  "rmarkdown", "hexbin", "lintr", "styler", "gapminder", "gridExtra",
  "hms", "RColorBrewer", "cowsay", "kableExtra", "janitor", "ggrepel"
)
install.packages(my_packages, repos = "http://cran.rstudio.com")
library(tidyverse)
library(lintr)
```

# 2.1

```{r, echo = TRUE}
dbl <- pi
int <- 1L
char <- "character"
bool <- TRUE
```

```{r, echo = TRUE}
x <- TRUE
y <- "TRUE"
a <- 1
b <- 1L
d <- "1"
```

x is allowed as it is a boolean whereas if y is trying to be bool - it is probably not allowed, due to the fact that is a character. a is fine I think and so is b, but d is not?

# 2.2

```{r, echo = TRUE}
paste("pi is approx equal to", pi)
```
# 2.3

```{r, echo = TRUE}
x <- 1
if (x > 2) {
  print("x is greater than 2!")
} else {
  print("x is not greater than 2!")
}
```

# 2.4 
```{r, echo = TRUE}
normalise <- function(x) {
  (x - mean(x)) / sd(x)
}

x <- c(0, 2, -5, 1, 2)

y <- normalise(x)
```

# 2.5

```{r, echo = TRUE}
z <- c(5, 4, 3, 2, 1)

z1 <- c(5:1)

z2 <- rev(seq(1, 5, 1))

z3 <- seq(5, 1, length.out = 5)
```

# 2.6

```{r, echo = TRUE}
i <- rep(1:3, times = 2)
i
j <- rep(1:3, each = 2)
j
```

# 2.7 

```{r, echo = TRUE}
x <- TRUE
y <- "TRUE"
a <- 1
b <- "1"

c(a, a)
c(y, b)
c(a, x)
c(x, y)
```
# 2.8

```{r, echo = TRUE}
x <- c(1)
letters[x]

x <- c(3:5)
letters[x]

x <- c(5:3)
letters[x]

x <- seq(2, 26, by = 2)
letters[x]

x <- rev(seq(2, 26, by = 3))
letters[x]

# predict the following output

x <- letters
x[length(x)] <- "a"
x

x <- letters
x[1:length(x)] <- "bla"
x

x <- letters
x[1:length(x)] <- 0
x

x <- letters
x <- "a"
x

x <- letters
y <- 1:length(letters)
x[y > 10] <- "bla"
x

"b" == letters

"b" %in% letters # TRUE

c("b", "c") %in% letters
which(letters == "c") # tells you where in the vector c comes up

letters[27] # NA because there is no 27th letter of the alphabet
```
# 2.9

```{r, echo = TRUE}
count_na <- function(my_vector) {
  count <- 0
  for (i in 1:length(my_vector)) {
    if (is.na(my_vector[i])) {
      count <- count + 1
    }
  }
  return(count)
}
count_na(c(1, 2, NA))

count_na2 <- function(my_vector) {
  sum(is.na(my_vector))
}
count_na2(c(1, 2, 3, 4, NA, NA))
```
# 2.10

```{r, echo = FALSE, error = FALSE}
# c(TRUE, TRUE) && c(TRUE, FALSE)
# Error in c(TRUE, TRUE) && c(TRUE, FALSE) :
#  'length = 2' in coercion to 'logical(1)
```
